import = [
"~/.config/alacritty/themes/themes/monnlight_ii_vscode.toml",
"~/.config/alacritty/themes/themes/nightfly.toml"
]
[window]
padding.x = 10
padding.y = 10

decorations = "ButtonLess"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 16
